[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "d57d1f68e68ea22636e16d200028cbbdf7254fd8"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "50c4da0fa82dec88db99e940fdfdbc3b118cac66cd6eba9413cbd02557368aca"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "92b2060092f0c152eba1fbb26f567ea8aa289ffe"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "7f2e8fdedc5b438656b676c1916369cd6299569f5d3f854057cc9c910308510d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "75ba44a3c1c6cfc711dd1bf624df930f05c2543d"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "887e507de3f3141295697bc3ff6ddf876669b55d12885af5c0f654454c67108b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "4040e4691c58232452e2e0a7412fde4f2b644855"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "365564643494242a201c55ba9fbf602d21df4dc45fef13d3daa109ed35d89844"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "c330dad4cb62a64d59ba14149b46862954477334"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "a44b2c989e42d1ad0ade996098f7a4d376ea81d3b64aaef8041f434c1dfa5267"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "fa326946fd32fd77db4e7a891e1c0694fd3e33fb"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "313c72f008bb7716f83c28b45dea3ad74f9fed717d3fd8484889d1e86bda11c5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "7996fdce633769ce1bb7c0600b2536353075bbe6"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "874fbccb81347cc80cbe562422a9b5e960114fab7fed5618e0ec67365d182fd9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "2f99293a4153b1d9f17ee7fe68eff62f4315b544"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "bb2486d4b4fd179208d55a231ae80c4b87e87666ebad5027e7116c2fa2dc52aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.100+0/GAP_pkg_datastructures.v0.300.100.x86_64-unknown-freebsd.tar.gz"
