[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "170666f912374c0b6edb3e55dc29348ce3c951e5"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "a3e5e6f8bb85f6d4648fea53e2b0936b607c8683c873bdbb705e5770a3bb8f9f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "ea060ec9abcbf348dc345cdfe87cf01707e9634d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "a1a77aee8fe87d5270f835e356a4266841b54cb79a04e8704c93b77846bcb938"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "c2bce6fdcbb26e9c1bde5752c15582c330c29ad3"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "de2b2d553252cca4116e7545c9b6c77dfce1767d48af1ff630b629866172b5c2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "61a5c77780efa5bce248f4485a5f1439d5548c14"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "96b18df6c2f9543721632e4da02dc0ad5b41f9f9e868b6c777aa0b52306347df"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "69704273ba364d532826e7f2db55a636e7be6f84"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "3921956b9d3ab381005b9228ef4b1ca9996f66e91145d00602c2b8d935742433"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "18db9e26641fe5231d1cd362b209862d9ebfb101"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "2eb22f424088161cdf8d727e3d0c69a0a3bc9a1f1bf4d8a58c0be64cb1a9eb85"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "b0b3158b044e7d45d556de6a88d891ea54f3eb9f"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "707065c1f1d8e64d157b4cd2ffc310629369f0891668dd9b40b79ee1d66014cb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "ddb432f4ad1d8ed25ad906546bbbd99ed56ed77e"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "012facc6ccfa753eef27233ac5ebd917b3532063293ae9fb05e4ad443f248237"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.300.1+0/GAP_pkg_datastructures.v0.300.1.x86_64-unknown-freebsd.tar.gz"
