[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "07ffb3a921656f6ce3273c348bda5a2eb18a3004"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "be21e8b10f4d6289af854ad2ff8921198a9c3d49826ddcbcf1f8ea69148214a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "c3f3dd7d3a8a5d7ea953519bfe03d5d0b705abb5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "30764fcf206f42b4673872b78a5e2266641a76030c7c7e7fe81c0ff78aa85c32"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "5bb12a864a72186cbda85df21688018a0e45a6b3"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "eec4fc476b8a20f629475666bb29d69a15dfebad752cbeb497a4545454039f96"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "160080d21b9cf0e00ec35c219ef7616858e9590e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "08302049d782f3d44772d13ba7a19e9bb6995c253df079707b9350a467441090"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "3fe9bcc782a087307e051002b55e4022257f29d8"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "bf8e5a118584583ba095c012c82ea1fbf36249c3e0e85f2cb8dd3e47f6c714f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "4715d7b594ba7eeecedb557992a9a33c3df4d236"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "c931110b715315c9ef596c16182a901428824084e554bddac29727aff625b41c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "bdcdc31748bf385774539cf861a44d794e3ca7db"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "00b7f6bed4d284c23f3f3347959e6d34cde4d59199490191d054e9ee449ac997"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "a725f032bb360b23151ef790b9be2c4ab3adbc1a"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "6eeda36729033907be17c8237b6d59f4bff67e1875f5093b568e879015590a1d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+1/GAP_pkg_datastructures.v0.200.700.x86_64-unknown-freebsd.tar.gz"
