[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "bb0fd69c0746782e31792dc5c0eb1987994b4f49"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "ff9368013c727361b188cdd8adc19022854707045673d158d5ca2542b39b084b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "2ccde3c6efc008f3b84d55f79b819a7fd40d7d22"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "bcf2acddef755a19729ab33acc16de163b86e4ed797d6a17b41c8cef156ab150"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "855d918d85874e3128dbc2c83c6e1ceff80f8b02"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "acde5561b61b3267e0011f435eccb02d583175900d25e4cdf6ca4a53f78ed5f0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "358b2c4ddc21f992f5487d213fcd22de63f0aee5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "c87e7ee3d972278f83de06ea1847af08d76f08301474f46bd9a170e6aa54cd99"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "562ecbf47fbc47da4ab4f22fc28e7a88d9b61193"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "ad6ef6e2e3c264cb3ea2d86f48e7d1693a50620a0c8c579de06005a44e729ebb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "06495b5a7d21027b9295290b9da9a70e6212c5fe"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "8c513090996ec677df2835df74ff339247b070d8540c4440e233ccb8e7fccad1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "5f3e7657728837d7efbf82e7409e70d7a617a478"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "6a0d43a44dad8c5c5444362f2ca2dce89742511aa3633c1b55214bdd245f0d04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "17004c22184f79e9e09ba23400f62e8298d09546"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "bfd0fcda6c946d5cca81be6eedcc2c970938989c4975647fbb436cc2c42c4ace"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.701+1/GAP_pkg_datastructures.v0.200.701.x86_64-unknown-freebsd.tar.gz"
