[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "05bdd4f586d5e866a1e84ac937a9bad75ae1eb2f"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "8122a7371493fa4e2e3130f3ff8e4fcd40f016c09d235c71064a07021abfb115"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "35d5fed550c56cab9c7a33fd22a5dc723c42b9d4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "54028d5cee92d1a89b50bc1eda52f98cef00c038d47f4de214030d6ca713df36"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "e947e465369daf4589db35bd2cc5501654e00c04"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "68289bdcc4887fb71a13e7947f18118797a3e7837b0f4ff4a2520586c8faabb9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "88ab651fc69594016ce2c73d356c66c1f3b6604f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "558d0fc8188447afb0595981512df44c3e5848ff5bdafae5ea6d59568fb89ac6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "acabfe615f1ac015cdc44c7d04b4b53ae62f6e6c"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "1994b7e8b9ac5ef10ce0511d5e1b6cb245e01cd6f70c377fbe35712bdecb2a69"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "4d79d7b1f62ff8b3b55de1c0a585f724b91c4953"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "fca60727f34852b03736fa4c4535ba1f65f8b48358d9c3d00c1a20c1f8886fd8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "9d127ef7b9ddebe88f16bb52e68f44198976f19f"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "da8f67da3fc3f063b3eb1b8e44e738a9825c22d94d17dfabc5abb650582206ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "6cc288044f9ac8fb77b34159dc3af7e1f1e492bc"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "21b0b192c623e89d0f733300b708c4ff45dcd2c3ee7dcd809b1aa814829a6451"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.601+0/GAP_pkg_datastructures.v0.200.601.x86_64-unknown-freebsd.tar.gz"
