[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "34e1bc18b7bc1e701d8d9bd69dc4afe7d18e7586"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "9590c60f714fe09856e47f69949bb64ba01323f6adc1ce3ba4451a475d5d76a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "1430968a9dab49beae09f5b8ad0ced5c596617d8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "acaff223206f105b4e69a0be6f5f757b4f01d416309ad168a6024bcf31f07855"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "aarch64"
git-tree-sha1 = "1423930a57f57363be6f346279785302fa1a30f4"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "2943ece3a872c4d49640d5086c113a91e0c7dbb7ef117d7d0670b5ad4947a275"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.aarch64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "powerpc64le"
git-tree-sha1 = "0f6572fea4587d5bd174a283399eec12d16af7a5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "096676694f64f577a932cedcdfb84d600c3fc7e7fc83023121131e05228f839f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "c57a0b11007c0e3c85234e8751acc493e50d9b4b"
os = "macos"

    [[GAP_pkg_datastructures.download]]
    sha256 = "23bb9d2cee43a5380e003e9f547ad52fdce8df33689ed8488dc72830b47109a6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "9deb46684924c7ebafa74826d79b7614a1c949b3"
libc = "glibc"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "92ee4eb936debc478052d9f5ea171a8210988ae171891081164e6866c96f484d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "ea4d712949ed85e8709b9953e0e1d560d2273490"
libc = "musl"
os = "linux"

    [[GAP_pkg_datastructures.download]]
    sha256 = "d143d395eb62062c295ad7ac64455bfb92ee1e79859d7769f340b7172a9f6260"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.x86_64-linux-musl.tar.gz"
[[GAP_pkg_datastructures]]
arch = "x86_64"
git-tree-sha1 = "ae2fdc9ce46f6db7d472394ab10372dc2331066b"
os = "freebsd"

    [[GAP_pkg_datastructures.download]]
    sha256 = "c0e3a15ffb22de72f2598b0ac730a7d8f7bb7a36ce0336971f0496d6d95d7e04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_datastructures_jll.jl/releases/download/GAP_pkg_datastructures-v0.200.700+0/GAP_pkg_datastructures.v0.200.700.x86_64-unknown-freebsd.tar.gz"
